org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

mod_version = 0.1.0
maven_group = martydevs.marty
archives_name = marty
enabled_platforms = fabric,neoforge

minecraft_version = 26.2

architectury_api_version = 21.0.7
fabric_loader_version = 0.19.3
fabric_api_version = 0.157.0+26.2
neoforge_version = 26.2.0.52-beta

# Metadata
description=MapartCraft but better and as a mod.