modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "marty"
version = "${version}"
displayName = "Marty"
description = '''
MapartCraft but better and as a mod.
'''
#logoFile = ""

[[dependencies.marty]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.marty]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.marty]]
modId = "architectury"
type = "required"
versionRange = "[21.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "marty.mixins.json"
